version: '2.10.2'

services:
  olympus-discord-bot:
    build: .
    image: shredmetal/olympus-discord-bot:latest
    environment:
      - DISCORD_BOT_TOKEN
      - TROUBLESHOOTING_CHANNEL_ID
      - COMMUNITY_SUPPORT_CHANNEL_ID
      - SUPPORT_REQUESTS_ID
